# Generated by Django 5.1.6 on 2025-03-03 23:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ecommerce", "0002_remove_category_category_alter_product_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[
                    ("consumer_goods", "สินค้าอุปโภคบริโภค"),
                    ("beverages", "เครื่องดื่ม"),
                    ("snacks", "ขนมขบเคี้ยวและของกินเล่น"),
                    ("household_items", "ของใช้ในครัวเรือน"),
                    ("personal_items", "ของใช้ส่วนตัว"),
                    ("general_items", "ของใช้ทั่วไป"),
                    ("frozen_items", "สินค้าแช่เย็นและแช่แข็ง"),
                    ("cigarettes_alcohol", "บุหรี่และเครื่องดื่มแอลกอฮอล์"),
                ],
                max_length=50,
            ),
        ),
    ]
